
# -*- coding: utf-8 -*-
"""
Created on Sun Nov  8 14:11:29 2020

@author: Rick
"""

#!/usr/bin/env python3
# PUMP conversion factor 1 ~ 50ul  ?
from machine import *
from time import sleep
LINEVOL_A = 5

def countdown(t):
	while t:
		mins, secs = divmod(t, 60)
		timer = '{:02d}:{:02d}'.format(mins, secs)
		print(timer, end="\r")
		sleep(1)
		t -=1


print('STARTING...')
connect()
home()
set_heater(47)
cassette_contact()

mux_to(AIR)
move('pump', 40, speed=10)
wait_move_done()
sleep(1)
mux_to(SAMPLE_A)
move('pump', 0, speed=1)
wait_move_done()
sleep(1)

print('ADDING FORMALIN')
mux_to(FORMALIN)
sleep(1)
move('pump', 30, speed=5)
wait_move_done()
sleep(5)
mux_to(SAMPLE_A)
sleep(1)
move('pump',4, speed=1)
wait_move_done()
countdown(1200)

print('MEOH WASHING SAMPLE')
mux_to(MEOH)
wait_move_done()
sleep(1)
move('pump', 30, speed=10)
wait_move_done()
sleep(2)
mux_to(SAMPLE_A)
move('pump', (30-LINEVOL_A), speed=1)
wait_move_done()
sleep(10)
move('pump', 2, speed=1)
countdown(80)
move('pump', 0, speed=1)
wait_move_done()
sleep(4)
mux_to(MEOH)
wait_move_done()
sleep(1)
move('pump',30, speed=1)
wait_move_done()
sleep(2)
mux_to(SAMPLE_A)
wait_move_done()
sleep(1)
move('pump', 0, speed=1)
wait_move_done()
countdown(4)

print('REMOVING MEOH WASH')
mux_to(SAMPLE_A)
move('pump', 40, speed=2)
wait_move_done()
sleep(10)
mux_to(WASTE)
move('pump', 0, speed=10)
wait_move_done()
sleep(5)

print('ADDING DYE')
mux_to(DYE) 
wait_move_done()
sleep(1)
move('pump', 20, speed=1)
wait_move_done()
sleep(5)
mux_to(SAMPLE_A)
sleep(1)
move('pump', LINEVOL_A, speed=1)
wait_move_done()
sleep(1)
countdown(600)

print('INCUBATING DYE')
num_cycles = 3
cycle_secs = 600
for x in range(num_cycles):
	print ('CYCLE : {:02d}'.format(x+1))
	mux_to(WASTE)
	sleep(2)
	move('pump', 0, speed=10)
	wait_move_done()
	sleep(1)
	mux_to(SAMPLE_A)
	sleep(2)
	move('pump', 30, speed=1)
	wait_move_done()
	sleep(5)
	move('pump', 13, speed=1)
	wait_move_done()
	print('CYCLE : {:02d} of {:02d}'.format(x+1, num_cycles))
	countdown(cycle_secs)

print('DONE WITH DYE')
mux_to(WASTE)
move('pump', 0, speed=10)
wait_move_done()
sleep(1)

print('ADDING BABB')
mux_to(BABB)
move('pump', 25, speed=1)
wait_move_done()
sleep(5)
mux_to(SAMPLE_A)
sleep(2)
move('pump', 8, speed=1)
wait_move_done()
countdown(120)
move('pump', 0, speed=0.3)
wait_move_done()
sleep(3)
countdown(240)
print('Specimen ejecting')
cassette_eject()

print('CLEANING_PREP')
move('pump', 20, speed=10)
wait_move_done()
mux_to(WASTE)
home()
wait_move_done()
move('pump', 0, speed=10)

print('REMOVING BABB')
mux_to(SAMPLE_A)
move('pump', 40, speed=10)
wait_move_done()
sleep(3)
mux_to(WASTE)
move('pump', 0, speed=10)
wait_move_done()
sleep(2)

print('WASHING LINE')
mux_to(MEOH)
move('pump', 20, speed=10)
wait_move_done()
sleep(1)
mux_to(SAMPLE_A)
move('pump', 15, speed=0.3)
wait_move_done()
sleep(1)
move('pump', 30, speed=5)
wait_move_done()
mux_to(WASTE)
move('pump', 0, speed=10)

print('READY FOR NEW SAMPLE')
