# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '200330_SampleMon1stacksup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.protSel = QtWidgets.QWidget()
        self.protSel.setObjectName("protSel")
        self.pushButton = QtWidgets.QPushButton(self.protSel)
        self.pushButton.setGeometry(QtCore.QRect(40, 290, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.protSel)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.protSel)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 370, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.protSel)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 260, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.protSel)
        self.label.setGeometry(QtCore.QRect(50, 40, 121, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.protSel)
        self.label_2.setGeometry(QtCore.QRect(410, 30, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.protSel)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 201, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.protSel)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 290, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.listWidget = QtWidgets.QListWidget(self.protSel)
        self.listWidget.setGeometry(QtCore.QRect(30, 80, 291, 192))
        self.listWidget.setObjectName("listWidget")
        
        self.stackedWidget.addWidget(self.protSel)
        self.protEditor = QtWidgets.QWidget()
        self.protEditor.setObjectName("protEditor")
        self.pushButton_9 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_9.setGeometry(QtCore.QRect(702, 50, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_10.setGeometry(QtCore.QRect(702, 300, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_7.setGeometry(QtCore.QRect(702, 110, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_8.setGeometry(QtCore.QRect(702, 250, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_6 = QtWidgets.QLabel(self.protEditor)
        self.label_6.setGeometry(QtCore.QRect(200, 10, 140, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.protEditor)
        self.lineEdit.setGeometry(QtCore.QRect(350, 10, 142, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setInputMask("")
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_12 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 0, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.listWidget_2 = QtWidgets.QListWidget(self.protEditor)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 50, 110, 368))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listWidget_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget_2.setAlternatingRowColors(True)
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 0, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.listWidget_3 = QtWidgets.QListWidget(self.protEditor)
        self.listWidget_3.setGeometry(QtCore.QRect(111, 50, 590, 368))
        self.listWidget_3.setObjectName("listWidget_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.protEditor)
        self.pushButton_11.setGeometry(QtCore.QRect(702, 368, 80, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.stackedWidget.addWidget(self.protEditor)
        
        self.mainMonitor = QtWidgets.QWidget()
        self.mainMonitor.setObjectName("mainMonitor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainMonitor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StackedWidget1 = QtWidgets.QStackedWidget(self.mainMonitor)
        self.StackedWidget1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget1.sizePolicy().hasHeightForWidth())
        
        self.StackedWidget1.setSizePolicy(sizePolicy)
        self.StackedWidget1.setAcceptDrops(False)
        self.StackedWidget1.setObjectName("StackedWidget1")
        self.S1Page1 = QtWidgets.QWidget()
        self.S1Page1.setObjectName("S1Page1")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.S1Page1)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.progressBar_1 = QtWidgets.QProgressBar(self.S1Page1)
        self.progressBar_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_1.sizePolicy().hasHeightForWidth())
        self.progressBar_1.setSizePolicy(sizePolicy)
        self.progressBar_1.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_1.setProperty("value", 19)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout_29.addWidget(self.progressBar_1, 9, 0, 1, 2)
        
        self.sampName_1 = QtWidgets.QLabel(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_1.sizePolicy().hasHeightForWidth())
        self.sampName_1.setSizePolicy(sizePolicy)
        self.sampName_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_1.setObjectName("sampName_1")
        self.gridLayout_29.addWidget(self.sampName_1, 1, 0, 1, 1)
        
        self.stepLab_1 = QtWidgets.QLabel(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_1.sizePolicy().hasHeightForWidth())
        self.stepLab_1.setSizePolicy(sizePolicy)
        self.stepLab_1.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_1.setObjectName("stepLab_1")
        self.gridLayout_29.addWidget(self.stepLab_1, 7, 0, 1, 1)
        
        self.protName_1 = QtWidgets.QLabel(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_1.sizePolicy().hasHeightForWidth())
        self.protName_1.setSizePolicy(sizePolicy)
        self.protName_1.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_1.setObjectName("protName_1")
        self.gridLayout_29.addWidget(self.protName_1, 1, 1, 1, 1)
        
        self.casN_11 = QtWidgets.QLabel(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_11.sizePolicy().hasHeightForWidth())
        self.casN_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_11.setFont(font)
        self.casN_11.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_11.setObjectName("casN_11")
        self.gridLayout_29.addWidget(self.casN_11, 0, 0, 1, 2)
        
        self.time_1 = QtWidgets.QLabel(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_1.sizePolicy().hasHeightForWidth())
        self.time_1.setSizePolicy(sizePolicy)
        self.time_1.setAlignment(QtCore.Qt.AlignCenter)
        self.time_1.setObjectName("time_1")
        self.gridLayout_29.addWidget(self.time_1, 7, 1, 1, 1)
        
        self.stopB_1 = QtWidgets.QPushButton(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_1.sizePolicy().hasHeightForWidth())
        self.stopB_1.setSizePolicy(sizePolicy)
        self.stopB_1.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_1.setObjectName("stopB_1")
        self.gridLayout_29.addWidget(self.stopB_1, 10, 0, 1, 1)
        
        self.runDetB_1 = QtWidgets.QPushButton(self.S1Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_1.sizePolicy().hasHeightForWidth())
        self.runDetB_1.setSizePolicy(sizePolicy)
        self.runDetB_1.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_1.setAutoDefault(False)
        self.runDetB_1.setDefault(False)
        self.runDetB_1.setFlat(False)
        self.runDetB_1.setObjectName("runDetB_1")
        self.gridLayout_29.addWidget(self.runDetB_1, 10, 1, 1, 1)
        
        self.StackedWidget1.addWidget(self.S1Page1)
        
        self.S1Page2 = QtWidgets.QWidget()
        self.S1Page2.setObjectName("S1Page2")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.S1Page2)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.casN_12 = QtWidgets.QLabel(self.S1Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_12.sizePolicy().hasHeightForWidth())
        self.casN_12.setSizePolicy(sizePolicy)
        self.casN_12.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_12.setFont(font)
        self.casN_12.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_12.setObjectName("casN_12")
        self.gridLayout_30.addWidget(self.casN_12, 0, 0, 1, 2)
        self.setupB_1 = QtWidgets.QPushButton(self.S1Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_1.sizePolicy().hasHeightForWidth())
        self.setupB_1.setSizePolicy(sizePolicy)
        self.setupB_1.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_1.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_1.setObjectName("setupB_1")
        self.gridLayout_30.addWidget(self.setupB_1, 2, 0, 1, 1)
        self.runDefault_1 = QtWidgets.QPushButton(self.S1Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_1.sizePolicy().hasHeightForWidth())
        self.runDefault_1.setSizePolicy(sizePolicy)
        self.runDefault_1.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_1.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_1.setObjectName("runDefault_1")
        self.gridLayout_30.addWidget(self.runDefault_1, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem1, 3, 0, 1, 2)
        self.StackedWidget1.addWidget(self.S1Page2)
        self.S1Page3 = QtWidgets.QWidget()
        self.S1Page3.setObjectName("S1Page3")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.S1Page3)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.casN_13 = QtWidgets.QLabel(self.S1Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_13.sizePolicy().hasHeightForWidth())
        self.casN_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_13.setFont(font)
        self.casN_13.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_13.setObjectName("casN_13")
        self.gridLayout_31.addWidget(self.casN_13, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem2, 1, 0, 1, 1)
        self.noCas_1 = QtWidgets.QLabel(self.S1Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_1.sizePolicy().hasHeightForWidth())
        self.noCas_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_1.setFont(font)
        self.noCas_1.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_1.setObjectName("noCas_1")
        self.gridLayout_31.addWidget(self.noCas_1, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem3, 3, 0, 1, 1)
        self.StackedWidget1.addWidget(self.S1Page3)
        self.gridLayout_2.addWidget(self.StackedWidget1, 0, 0, 1, 1)
        self.StackedWidget2 = QtWidgets.QStackedWidget(self.mainMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget2.sizePolicy().hasHeightForWidth())
        self.StackedWidget2.setSizePolicy(sizePolicy)
        self.StackedWidget2.setObjectName("StackedWidget2")
        self.S2Page1 = QtWidgets.QWidget()
        self.S2Page1.setObjectName("S2Page1")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.S2Page1)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.casN_21 = QtWidgets.QLabel(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_21.sizePolicy().hasHeightForWidth())
        self.casN_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_21.setFont(font)
        self.casN_21.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_21.setObjectName("casN_21")
        self.gridLayout_35.addWidget(self.casN_21, 0, 0, 1, 2)
        self.sampName_2 = QtWidgets.QLabel(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_2.sizePolicy().hasHeightForWidth())
        self.sampName_2.setSizePolicy(sizePolicy)
        self.sampName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_2.setObjectName("sampName_2")
        self.gridLayout_35.addWidget(self.sampName_2, 1, 0, 1, 1)
        self.protName_2 = QtWidgets.QLabel(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_2.sizePolicy().hasHeightForWidth())
        self.protName_2.setSizePolicy(sizePolicy)
        self.protName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_2.setObjectName("protName_2")
        self.gridLayout_35.addWidget(self.protName_2, 1, 1, 1, 1)
        self.stepLab_2 = QtWidgets.QLabel(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_2.sizePolicy().hasHeightForWidth())
        self.stepLab_2.setSizePolicy(sizePolicy)
        self.stepLab_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_2.setObjectName("stepLab_2")
        self.gridLayout_35.addWidget(self.stepLab_2, 3, 0, 1, 1)
        self.time_2 = QtWidgets.QLabel(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_2.sizePolicy().hasHeightForWidth())
        self.time_2.setSizePolicy(sizePolicy)
        self.time_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_2.setObjectName("time_2")
        self.gridLayout_35.addWidget(self.time_2, 3, 1, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.S2Page1)
        self.progressBar_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_2.setProperty("value", 19)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_35.addWidget(self.progressBar_2, 4, 0, 1, 2)
        self.stopB_2 = QtWidgets.QPushButton(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_2.sizePolicy().hasHeightForWidth())
        self.stopB_2.setSizePolicy(sizePolicy)
        self.stopB_2.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_2.setObjectName("stopB_2")
        self.gridLayout_35.addWidget(self.stopB_2, 5, 0, 1, 1)
        self.runDetB_2 = QtWidgets.QPushButton(self.S2Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_2.sizePolicy().hasHeightForWidth())
        self.runDetB_2.setSizePolicy(sizePolicy)
        self.runDetB_2.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_2.setAutoDefault(False)
        self.runDetB_2.setDefault(False)
        self.runDetB_2.setFlat(False)
        self.runDetB_2.setObjectName("runDetB_2")
        self.gridLayout_35.addWidget(self.runDetB_2, 5, 1, 1, 1)
        self.StackedWidget2.addWidget(self.S2Page1)
        self.S2Page2 = QtWidgets.QWidget()
        self.S2Page2.setObjectName("S2Page2")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.S2Page2)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.setupB_2 = QtWidgets.QPushButton(self.S2Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_2.sizePolicy().hasHeightForWidth())
        self.setupB_2.setSizePolicy(sizePolicy)
        self.setupB_2.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_2.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_2.setObjectName("setupB_2")
        self.gridLayout_36.addWidget(self.setupB_2, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem4, 2, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem5, 4, 0, 1, 2)
        self.casN_22 = QtWidgets.QLabel(self.S2Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_22.sizePolicy().hasHeightForWidth())
        self.casN_22.setSizePolicy(sizePolicy)
        self.casN_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_22.setFont(font)
        self.casN_22.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_22.setObjectName("casN_22")
        self.gridLayout_36.addWidget(self.casN_22, 1, 0, 1, 2)
        self.runDefault_2 = QtWidgets.QPushButton(self.S2Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_2.sizePolicy().hasHeightForWidth())
        self.runDefault_2.setSizePolicy(sizePolicy)
        self.runDefault_2.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_2.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_2.setObjectName("runDefault_2")
        self.gridLayout_36.addWidget(self.runDefault_2, 3, 1, 1, 1)
        self.StackedWidget2.addWidget(self.S2Page2)
        self.S2Page3 = QtWidgets.QWidget()
        self.S2Page3.setObjectName("S2Page3")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.S2Page3)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.casN_23 = QtWidgets.QLabel(self.S2Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_23.sizePolicy().hasHeightForWidth())
        self.casN_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_23.setFont(font)
        self.casN_23.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_23.setObjectName("casN_23")
        self.gridLayout_37.addWidget(self.casN_23, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem6, 1, 0, 1, 1)
        self.noCas_2 = QtWidgets.QLabel(self.S2Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_2.sizePolicy().hasHeightForWidth())
        self.noCas_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_2.setFont(font)
        self.noCas_2.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_2.setObjectName("noCas_2")
        self.gridLayout_37.addWidget(self.noCas_2, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem7, 3, 0, 1, 1)
        self.StackedWidget2.addWidget(self.S2Page3)
        self.gridLayout_2.addWidget(self.StackedWidget2, 0, 1, 1, 1)
        self.StackedWidget3 = QtWidgets.QStackedWidget(self.mainMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget3.sizePolicy().hasHeightForWidth())
        self.StackedWidget3.setSizePolicy(sizePolicy)
        self.StackedWidget3.setObjectName("StackedWidget3")
        self.S3Page1 = QtWidgets.QWidget()
        self.S3Page1.setObjectName("S3Page1")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.S3Page1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.casN_31 = QtWidgets.QLabel(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_31.sizePolicy().hasHeightForWidth())
        self.casN_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_31.setFont(font)
        self.casN_31.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_31.setObjectName("casN_31")
        self.gridLayout_26.addWidget(self.casN_31, 0, 0, 1, 2)
        self.sampName_3 = QtWidgets.QLabel(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_3.sizePolicy().hasHeightForWidth())
        self.sampName_3.setSizePolicy(sizePolicy)
        self.sampName_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_3.setObjectName("sampName_3")
        self.gridLayout_26.addWidget(self.sampName_3, 1, 0, 1, 1)
        self.protName_3 = QtWidgets.QLabel(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_3.sizePolicy().hasHeightForWidth())
        self.protName_3.setSizePolicy(sizePolicy)
        self.protName_3.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_3.setObjectName("protName_3")
        self.gridLayout_26.addWidget(self.protName_3, 1, 1, 1, 1)
        self.stepLab_3 = QtWidgets.QLabel(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_3.sizePolicy().hasHeightForWidth())
        self.stepLab_3.setSizePolicy(sizePolicy)
        self.stepLab_3.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_3.setObjectName("stepLab_3")
        self.gridLayout_26.addWidget(self.stepLab_3, 3, 0, 1, 1)
        self.time_3 = QtWidgets.QLabel(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_3.sizePolicy().hasHeightForWidth())
        self.time_3.setSizePolicy(sizePolicy)
        self.time_3.setAlignment(QtCore.Qt.AlignCenter)
        self.time_3.setObjectName("time_3")
        self.gridLayout_26.addWidget(self.time_3, 3, 1, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.S3Page1)
        self.progressBar_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_3.sizePolicy().hasHeightForWidth())
        self.progressBar_3.setSizePolicy(sizePolicy)
        self.progressBar_3.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_3.setProperty("value", 19)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout_26.addWidget(self.progressBar_3, 4, 0, 1, 2)
        self.stopB_3 = QtWidgets.QPushButton(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_3.sizePolicy().hasHeightForWidth())
        self.stopB_3.setSizePolicy(sizePolicy)
        self.stopB_3.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_3.setObjectName("stopB_3")
        self.gridLayout_26.addWidget(self.stopB_3, 5, 0, 1, 1)
        self.runDetB_3 = QtWidgets.QPushButton(self.S3Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_3.sizePolicy().hasHeightForWidth())
        self.runDetB_3.setSizePolicy(sizePolicy)
        self.runDetB_3.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_3.setAutoDefault(False)
        self.runDetB_3.setDefault(False)
        self.runDetB_3.setFlat(False)
        self.runDetB_3.setObjectName("runDetB_3")
        self.gridLayout_26.addWidget(self.runDetB_3, 5, 1, 1, 1)
        self.StackedWidget3.addWidget(self.S3Page1)
        self.S3Page2 = QtWidgets.QWidget()
        self.S3Page2.setObjectName("S3Page2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.S3Page2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.casN_32 = QtWidgets.QLabel(self.S3Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_32.sizePolicy().hasHeightForWidth())
        self.casN_32.setSizePolicy(sizePolicy)
        self.casN_32.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_32.setFont(font)
        self.casN_32.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_32.setObjectName("casN_32")
        self.gridLayout_27.addWidget(self.casN_32, 0, 0, 1, 2)
        self.setupB_3 = QtWidgets.QPushButton(self.S3Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_3.sizePolicy().hasHeightForWidth())
        self.setupB_3.setSizePolicy(sizePolicy)
        self.setupB_3.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_3.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_3.setObjectName("setupB_3")
        self.gridLayout_27.addWidget(self.setupB_3, 2, 0, 1, 1)
        self.runDefault_3 = QtWidgets.QPushButton(self.S3Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_3.sizePolicy().hasHeightForWidth())
        self.runDefault_3.setSizePolicy(sizePolicy)
        self.runDefault_3.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_3.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_3.setObjectName("runDefault_3")
        self.gridLayout_27.addWidget(self.runDefault_3, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem8, 1, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem9, 3, 0, 1, 2)
        self.StackedWidget3.addWidget(self.S3Page2)
        self.S3Page3 = QtWidgets.QWidget()
        self.S3Page3.setObjectName("S3Page3")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.S3Page3)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.casN_33 = QtWidgets.QLabel(self.S3Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_33.sizePolicy().hasHeightForWidth())
        self.casN_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_33.setFont(font)
        self.casN_33.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_33.setObjectName("casN_33")
        self.gridLayout_28.addWidget(self.casN_33, 0, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem10, 1, 0, 1, 2)
        self.noCas_3 = QtWidgets.QLabel(self.S3Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_3.sizePolicy().hasHeightForWidth())
        self.noCas_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_3.setFont(font)
        self.noCas_3.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_3.setObjectName("noCas_3")
        self.gridLayout_28.addWidget(self.noCas_3, 6, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem11, 7, 0, 1, 2)
        self.StackedWidget3.addWidget(self.S3Page3)
        self.gridLayout_2.addWidget(self.StackedWidget3, 0, 2, 1, 1)
        self.StackedWidget4 = QtWidgets.QStackedWidget(self.mainMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget4.sizePolicy().hasHeightForWidth())
        self.StackedWidget4.setSizePolicy(sizePolicy)
        self.StackedWidget4.setObjectName("StackedWidget4")
        self.S4Page1 = QtWidgets.QWidget()
        self.S4Page1.setObjectName("S4Page1")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.S4Page1)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.casN_41 = QtWidgets.QLabel(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_41.sizePolicy().hasHeightForWidth())
        self.casN_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_41.setFont(font)
        self.casN_41.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_41.setObjectName("casN_41")
        self.gridLayout_32.addWidget(self.casN_41, 0, 0, 1, 2)
        self.sampName_4 = QtWidgets.QLabel(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_4.sizePolicy().hasHeightForWidth())
        self.sampName_4.setSizePolicy(sizePolicy)
        self.sampName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_4.setObjectName("sampName_4")
        self.gridLayout_32.addWidget(self.sampName_4, 1, 0, 1, 1)
        self.protName_4 = QtWidgets.QLabel(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_4.sizePolicy().hasHeightForWidth())
        self.protName_4.setSizePolicy(sizePolicy)
        self.protName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_4.setObjectName("protName_4")
        self.gridLayout_32.addWidget(self.protName_4, 1, 1, 1, 1)
        self.stepLab_4 = QtWidgets.QLabel(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_4.sizePolicy().hasHeightForWidth())
        self.stepLab_4.setSizePolicy(sizePolicy)
        self.stepLab_4.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_4.setObjectName("stepLab_4")
        self.gridLayout_32.addWidget(self.stepLab_4, 3, 0, 1, 1)
        self.time_4 = QtWidgets.QLabel(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_4.sizePolicy().hasHeightForWidth())
        self.time_4.setSizePolicy(sizePolicy)
        self.time_4.setAlignment(QtCore.Qt.AlignCenter)
        self.time_4.setObjectName("time_4")
        self.gridLayout_32.addWidget(self.time_4, 3, 1, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.S4Page1)
        self.progressBar_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_4.sizePolicy().hasHeightForWidth())
        self.progressBar_4.setSizePolicy(sizePolicy)
        self.progressBar_4.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_4.setProperty("value", 19)
        self.progressBar_4.setTextVisible(True)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout_32.addWidget(self.progressBar_4, 4, 0, 1, 2)
        self.stopB_4 = QtWidgets.QPushButton(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_4.sizePolicy().hasHeightForWidth())
        self.stopB_4.setSizePolicy(sizePolicy)
        self.stopB_4.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_4.setObjectName("stopB_4")
        self.gridLayout_32.addWidget(self.stopB_4, 5, 0, 1, 1)
        self.runDetB_4 = QtWidgets.QPushButton(self.S4Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_4.sizePolicy().hasHeightForWidth())
        self.runDetB_4.setSizePolicy(sizePolicy)
        self.runDetB_4.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_4.setAutoDefault(False)
        self.runDetB_4.setDefault(False)
        self.runDetB_4.setFlat(False)
        self.runDetB_4.setObjectName("runDetB_4")
        self.gridLayout_32.addWidget(self.runDetB_4, 5, 1, 1, 1)
        self.StackedWidget4.addWidget(self.S4Page1)
        self.S4Page2 = QtWidgets.QWidget()
        self.S4Page2.setObjectName("S4Page2")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.S4Page2)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.casN_42 = QtWidgets.QLabel(self.S4Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_42.sizePolicy().hasHeightForWidth())
        self.casN_42.setSizePolicy(sizePolicy)
        self.casN_42.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_42.setFont(font)
        self.casN_42.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_42.setObjectName("casN_42")
        self.gridLayout_33.addWidget(self.casN_42, 0, 0, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem12, 1, 0, 1, 2)
        self.setupB_4 = QtWidgets.QPushButton(self.S4Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_4.sizePolicy().hasHeightForWidth())
        self.setupB_4.setSizePolicy(sizePolicy)
        self.setupB_4.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_4.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_4.setObjectName("setupB_4")
        self.gridLayout_33.addWidget(self.setupB_4, 2, 0, 1, 1)
        self.runDefault_4 = QtWidgets.QPushButton(self.S4Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_4.sizePolicy().hasHeightForWidth())
        self.runDefault_4.setSizePolicy(sizePolicy)
        self.runDefault_4.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_4.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_4.setObjectName("runDefault_4")
        self.gridLayout_33.addWidget(self.runDefault_4, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem13, 3, 0, 1, 2)
        self.StackedWidget4.addWidget(self.S4Page2)
        self.S4Page3 = QtWidgets.QWidget()
        self.S4Page3.setObjectName("S4Page3")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.S4Page3)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.casN_43 = QtWidgets.QLabel(self.S4Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_43.sizePolicy().hasHeightForWidth())
        self.casN_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_43.setFont(font)
        self.casN_43.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_43.setObjectName("casN_43")
        self.gridLayout_34.addWidget(self.casN_43, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem14, 1, 0, 1, 1)
        self.noCas_4 = QtWidgets.QLabel(self.S4Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_4.sizePolicy().hasHeightForWidth())
        self.noCas_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_4.setFont(font)
        self.noCas_4.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_4.setObjectName("noCas_4")
        self.gridLayout_34.addWidget(self.noCas_4, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem15, 3, 0, 1, 1)
        self.StackedWidget4.addWidget(self.S4Page3)
        self.gridLayout_2.addWidget(self.StackedWidget4, 1, 0, 1, 1)
        self.StackedWidget5 = QtWidgets.QStackedWidget(self.mainMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget5.sizePolicy().hasHeightForWidth())
        self.StackedWidget5.setSizePolicy(sizePolicy)
        self.StackedWidget5.setObjectName("StackedWidget5")
        self.S5Page1 = QtWidgets.QWidget()
        self.S5Page1.setObjectName("S5Page1")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.S5Page1)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.sampName_5 = QtWidgets.QLabel(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_5.sizePolicy().hasHeightForWidth())
        self.sampName_5.setSizePolicy(sizePolicy)
        self.sampName_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_5.setObjectName("sampName_5")
        self.gridLayout_20.addWidget(self.sampName_5, 2, 0, 1, 1)
        self.casN_51 = QtWidgets.QLabel(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_51.sizePolicy().hasHeightForWidth())
        self.casN_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_51.setFont(font)
        self.casN_51.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_51.setObjectName("casN_51")
        self.gridLayout_20.addWidget(self.casN_51, 0, 0, 1, 2)
        self.time_5 = QtWidgets.QLabel(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_5.sizePolicy().hasHeightForWidth())
        self.time_5.setSizePolicy(sizePolicy)
        self.time_5.setAlignment(QtCore.Qt.AlignCenter)
        self.time_5.setObjectName("time_5")
        self.gridLayout_20.addWidget(self.time_5, 4, 1, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.S5Page1)
        self.progressBar_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_5.sizePolicy().hasHeightForWidth())
        self.progressBar_5.setSizePolicy(sizePolicy)
        self.progressBar_5.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout_20.addWidget(self.progressBar_5, 6, 0, 1, 2)
        self.protName_5 = QtWidgets.QLabel(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_5.sizePolicy().hasHeightForWidth())
        self.protName_5.setSizePolicy(sizePolicy)
        self.protName_5.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_5.setObjectName("protName_5")
        self.gridLayout_20.addWidget(self.protName_5, 2, 1, 1, 1)
        self.stepLab_5 = QtWidgets.QLabel(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_5.sizePolicy().hasHeightForWidth())
        self.stepLab_5.setSizePolicy(sizePolicy)
        self.stepLab_5.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_5.setObjectName("stepLab_5")
        self.gridLayout_20.addWidget(self.stepLab_5, 4, 0, 1, 1)
        self.stopB_5 = QtWidgets.QPushButton(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_5.sizePolicy().hasHeightForWidth())
        self.stopB_5.setSizePolicy(sizePolicy)
        self.stopB_5.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_5.setObjectName("stopB_5")
        self.gridLayout_20.addWidget(self.stopB_5, 7, 0, 1, 1)
        self.runDetB_5 = QtWidgets.QPushButton(self.S5Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_5.sizePolicy().hasHeightForWidth())
        self.runDetB_5.setSizePolicy(sizePolicy)
        self.runDetB_5.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_5.setObjectName("runDetB_5")
        self.gridLayout_20.addWidget(self.runDetB_5, 7, 1, 1, 1)
        self.StackedWidget5.addWidget(self.S5Page1)
        self.S5Page2 = QtWidgets.QWidget()
        self.S5Page2.setObjectName("S5Page2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.S5Page2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.casN_52 = QtWidgets.QLabel(self.S5Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_52.sizePolicy().hasHeightForWidth())
        self.casN_52.setSizePolicy(sizePolicy)
        self.casN_52.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_52.setFont(font)
        self.casN_52.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_52.setObjectName("casN_52")
        self.gridLayout_21.addWidget(self.casN_52, 0, 0, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem16, 1, 0, 1, 2)
        self.setupB_5 = QtWidgets.QPushButton(self.S5Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_5.sizePolicy().hasHeightForWidth())
        self.setupB_5.setSizePolicy(sizePolicy)
        self.setupB_5.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_5.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_5.setObjectName("setupB_5")
        self.gridLayout_21.addWidget(self.setupB_5, 2, 0, 1, 1)
        self.runDefault_5 = QtWidgets.QPushButton(self.S5Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_5.sizePolicy().hasHeightForWidth())
        self.runDefault_5.setSizePolicy(sizePolicy)
        self.runDefault_5.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_5.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_5.setObjectName("runDefault_5")
        self.gridLayout_21.addWidget(self.runDefault_5, 2, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem17, 3, 0, 1, 2)
        self.StackedWidget5.addWidget(self.S5Page2)
        self.S5Page3 = QtWidgets.QWidget()
        self.S5Page3.setObjectName("S5Page3")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.S5Page3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.casN_53 = QtWidgets.QLabel(self.S5Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_53.sizePolicy().hasHeightForWidth())
        self.casN_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_53.setFont(font)
        self.casN_53.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_53.setObjectName("casN_53")
        self.gridLayout_22.addWidget(self.casN_53, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem18, 1, 0, 1, 1)
        self.noCas_5 = QtWidgets.QLabel(self.S5Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_5.sizePolicy().hasHeightForWidth())
        self.noCas_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_5.setFont(font)
        self.noCas_5.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_5.setObjectName("noCas_5")
        self.gridLayout_22.addWidget(self.noCas_5, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem19, 3, 0, 1, 1)
        self.StackedWidget5.addWidget(self.S5Page3)
        self.gridLayout_2.addWidget(self.StackedWidget5, 1, 1, 1, 1)
        self.StackedWidget6 = QtWidgets.QStackedWidget(self.mainMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedWidget6.sizePolicy().hasHeightForWidth())
        self.StackedWidget6.setSizePolicy(sizePolicy)
        self.StackedWidget6.setObjectName("StackedWidget6")
        self.S6Page1 = QtWidgets.QWidget()
        self.S6Page1.setObjectName("S6Page1")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.S6Page1)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.time_6 = QtWidgets.QLabel(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_6.sizePolicy().hasHeightForWidth())
        self.time_6.setSizePolicy(sizePolicy)
        self.time_6.setAlignment(QtCore.Qt.AlignCenter)
        self.time_6.setObjectName("time_6")
        self.gridLayout_23.addWidget(self.time_6, 4, 1, 1, 1)
        self.protName_6 = QtWidgets.QLabel(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protName_6.sizePolicy().hasHeightForWidth())
        self.protName_6.setSizePolicy(sizePolicy)
        self.protName_6.setAlignment(QtCore.Qt.AlignCenter)
        self.protName_6.setObjectName("protName_6")
        self.gridLayout_23.addWidget(self.protName_6, 2, 1, 1, 1)
        self.sampName_6 = QtWidgets.QLabel(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampName_6.sizePolicy().hasHeightForWidth())
        self.sampName_6.setSizePolicy(sizePolicy)
        self.sampName_6.setAlignment(QtCore.Qt.AlignCenter)
        self.sampName_6.setObjectName("sampName_6")
        self.gridLayout_23.addWidget(self.sampName_6, 2, 0, 1, 1)
        self.stepLab_6 = QtWidgets.QLabel(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepLab_6.sizePolicy().hasHeightForWidth())
        self.stepLab_6.setSizePolicy(sizePolicy)
        self.stepLab_6.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab_6.setObjectName("stepLab_6")
        self.gridLayout_23.addWidget(self.stepLab_6, 4, 0, 1, 1)
        self.progressBar_6 = QtWidgets.QProgressBar(self.S6Page1)
        self.progressBar_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_6.sizePolicy().hasHeightForWidth())
        self.progressBar_6.setSizePolicy(sizePolicy)
        self.progressBar_6.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setTextVisible(True)
        self.progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_6.setInvertedAppearance(False)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout_23.addWidget(self.progressBar_6, 5, 0, 1, 2)
        self.casN_61 = QtWidgets.QLabel(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_61.sizePolicy().hasHeightForWidth())
        self.casN_61.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_61.setFont(font)
        self.casN_61.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_61.setObjectName("casN_61")
        self.gridLayout_23.addWidget(self.casN_61, 0, 0, 1, 2)
        self.stopB_6 = QtWidgets.QPushButton(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopB_6.sizePolicy().hasHeightForWidth())
        self.stopB_6.setSizePolicy(sizePolicy)
        self.stopB_6.setMinimumSize(QtCore.QSize(50, 50))
        self.stopB_6.setObjectName("stopB_6")
        self.gridLayout_23.addWidget(self.stopB_6, 6, 0, 1, 1)
        self.runDetB_6 = QtWidgets.QPushButton(self.S6Page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDetB_6.sizePolicy().hasHeightForWidth())
        self.runDetB_6.setSizePolicy(sizePolicy)
        self.runDetB_6.setMinimumSize(QtCore.QSize(0, 50))
        self.runDetB_6.setObjectName("runDetB_6")
        self.gridLayout_23.addWidget(self.runDetB_6, 6, 1, 1, 1)
        self.StackedWidget6.addWidget(self.S6Page1)
        self.S6Page2 = QtWidgets.QWidget()
        self.S6Page2.setObjectName("S6Page2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.S6Page2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.casN_62 = QtWidgets.QLabel(self.S6Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_62.sizePolicy().hasHeightForWidth())
        self.casN_62.setSizePolicy(sizePolicy)
        self.casN_62.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_62.setFont(font)
        self.casN_62.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_62.setObjectName("casN_62")
        self.gridLayout_24.addWidget(self.casN_62, 0, 0, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem20, 1, 0, 1, 2)
        self.setupB_6 = QtWidgets.QPushButton(self.S6Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupB_6.sizePolicy().hasHeightForWidth())
        self.setupB_6.setSizePolicy(sizePolicy)
        self.setupB_6.setMinimumSize(QtCore.QSize(0, 50))
        self.setupB_6.setBaseSize(QtCore.QSize(0, 0))
        self.setupB_6.setObjectName("setupB_6")
        self.gridLayout_24.addWidget(self.setupB_6, 2, 0, 1, 1)
        self.runDefault_6 = QtWidgets.QPushButton(self.S6Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runDefault_6.sizePolicy().hasHeightForWidth())
        self.runDefault_6.setSizePolicy(sizePolicy)
        self.runDefault_6.setMinimumSize(QtCore.QSize(0, 50))
        self.runDefault_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.runDefault_6.setBaseSize(QtCore.QSize(0, 0))
        self.runDefault_6.setObjectName("runDefault_6")
        self.gridLayout_24.addWidget(self.runDefault_6, 2, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem21, 3, 0, 1, 2)
        self.StackedWidget6.addWidget(self.S6Page2)
        self.S6Page3 = QtWidgets.QWidget()
        self.S6Page3.setObjectName("S6Page3")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.S6Page3)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.casN_63 = QtWidgets.QLabel(self.S6Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.casN_63.sizePolicy().hasHeightForWidth())
        self.casN_63.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.casN_63.setFont(font)
        self.casN_63.setAlignment(QtCore.Qt.AlignCenter)
        self.casN_63.setObjectName("casN_63")
        self.gridLayout_25.addWidget(self.casN_63, 0, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem22, 1, 0, 1, 1)
        self.noCas_6 = QtWidgets.QLabel(self.S6Page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noCas_6.sizePolicy().hasHeightForWidth())
        self.noCas_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noCas_6.setFont(font)
        self.noCas_6.setAlignment(QtCore.Qt.AlignCenter)
        self.noCas_6.setObjectName("noCas_6")
        self.gridLayout_25.addWidget(self.noCas_6, 2, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem23, 3, 0, 1, 1)
        self.StackedWidget6.addWidget(self.S6Page3)
        self.gridLayout_2.addWidget(self.StackedWidget6, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.mainMonitor)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad_Program = QtWidgets.QMenu(self.menubar)
        self.menuLoad_Program.setObjectName("menuLoad_Program")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLoad_Program.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.StackedWidget1.setCurrentIndex(1)
        self.StackedWidget2.setCurrentIndex(1)
        self.StackedWidget3.setCurrentIndex(0)
        self.StackedWidget4.setCurrentIndex(0)
        self.StackedWidget5.setCurrentIndex(0)
        self.StackedWidget6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.pushButton_2.setText(_translate("MainWindow", "Load"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))
        self.pushButton_4.setText(_translate("MainWindow", "Edit"))
        self.label.setText(_translate("MainWindow", "Saved Protocols"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Cassette X -- Select Protocol"))
        self.pushButton_5.setText(_translate("MainWindow", "New"))
        self.pushButton_9.setText(_translate("MainWindow", "Remove"))
        self.pushButton_10.setText(_translate("MainWindow", "Save"))
        self.pushButton_7.setText(_translate("MainWindow", "Edit"))
        self.pushButton_8.setText(_translate("MainWindow", "Save As"))
        self.label_6.setText(_translate("MainWindow", "Protocol Name:"))
        self.lineEdit.setText(_translate("MainWindow", "untitled"))
        self.pushButton_12.setText(_translate("MainWindow", "Home"))
        self.pushButton_6.setText(_translate("MainWindow", "Back"))
        self.pushButton_11.setText(_translate("MainWindow", "Next"))
        self.progressBar_1.setFormat(_translate("MainWindow", "%p%"))
        self.sampName_1.setText(_translate("MainWindow", "SampleName"))
        self.stepLab_1.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.protName_1.setText(_translate("MainWindow", "ProtocolName"))
        self.casN_11.setText(_translate("MainWindow", "1"))
        self.time_1.setText(_translate("MainWindow", "HH:mm:ss"))
        self.stopB_1.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_1.setText(_translate("MainWindow", "Run Details"))
        self.casN_12.setText(_translate("MainWindow", "1"))
        self.setupB_1.setText(_translate("MainWindow", "Setup Run"))
        self.runDefault_1.setText(_translate("MainWindow", "Run Default"))
        self.casN_13.setText(_translate("MainWindow", "1"))
        self.noCas_1.setText(_translate("MainWindow", "No cassette detected"))
        self.casN_21.setText(_translate("MainWindow", "2"))
        self.sampName_2.setText(_translate("MainWindow", "SampleName"))
        self.protName_2.setText(_translate("MainWindow", "ProtocolName"))
        self.stepLab_2.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.time_2.setText(_translate("MainWindow", "HH:mm:ss"))
        self.progressBar_2.setFormat(_translate("MainWindow", "%p%"))
        self.stopB_2.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_2.setText(_translate("MainWindow", "Run Details"))
        self.setupB_2.setText(_translate("MainWindow", "Setup Run"))
        self.casN_22.setText(_translate("MainWindow", "2"))
        self.runDefault_2.setText(_translate("MainWindow", "Run Default"))
        self.casN_23.setText(_translate("MainWindow", "2"))
        self.noCas_2.setText(_translate("MainWindow", "No cassette detected"))
        self.casN_31.setText(_translate("MainWindow", "3"))
        self.sampName_3.setText(_translate("MainWindow", "SampleName"))
        self.protName_3.setText(_translate("MainWindow", "ProtocolName"))
        self.stepLab_3.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.time_3.setText(_translate("MainWindow", "HH:mm:ss"))
        self.progressBar_3.setFormat(_translate("MainWindow", "%p%"))
        self.stopB_3.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_3.setText(_translate("MainWindow", "Run Details"))
        self.casN_32.setText(_translate("MainWindow", "3"))
        self.setupB_3.setText(_translate("MainWindow", "Setup Run"))
        self.runDefault_3.setText(_translate("MainWindow", "Run Default"))
        self.casN_33.setText(_translate("MainWindow", "3"))
        self.noCas_3.setText(_translate("MainWindow", "No cassette detected"))
        self.casN_41.setText(_translate("MainWindow", "4"))
        self.sampName_4.setText(_translate("MainWindow", "SampleName"))
        self.protName_4.setText(_translate("MainWindow", "ProtocolName"))
        self.stepLab_4.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.time_4.setText(_translate("MainWindow", "HH:mm:ss"))
        self.progressBar_4.setFormat(_translate("MainWindow", "%p%"))
        self.stopB_4.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_4.setText(_translate("MainWindow", "Run Details"))
        self.casN_42.setText(_translate("MainWindow", "4"))
        self.setupB_4.setText(_translate("MainWindow", "Setup Run"))
        self.runDefault_4.setText(_translate("MainWindow", "Run Default"))
        self.casN_43.setText(_translate("MainWindow", "4"))
        self.noCas_4.setText(_translate("MainWindow", "No cassette detected"))
        self.sampName_5.setText(_translate("MainWindow", "SampleName"))
        self.casN_51.setText(_translate("MainWindow", "5"))
        self.time_5.setText(_translate("MainWindow", "HH:mm:ss"))
        self.protName_5.setText(_translate("MainWindow", "ProtocolName"))
        self.stepLab_5.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.stopB_5.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_5.setText(_translate("MainWindow", "Run Details"))
        self.casN_52.setText(_translate("MainWindow", "5"))
        self.setupB_5.setText(_translate("MainWindow", "Setup Run"))
        self.runDefault_5.setText(_translate("MainWindow", "Run Default"))
        self.casN_53.setText(_translate("MainWindow", "5"))
        self.noCas_5.setText(_translate("MainWindow", "No cassette detected"))
        self.time_6.setText(_translate("MainWindow", "HH:mm:ss"))
        self.protName_6.setText(_translate("MainWindow", "ProtocolName"))
        self.sampName_6.setText(_translate("MainWindow", "SampleName"))
        self.stepLab_6.setText(_translate("MainWindow", "\"Wash (1/6)\""))
        self.casN_61.setText(_translate("MainWindow", "6"))
        self.stopB_6.setText(_translate("MainWindow", "Stop Run"))
        self.runDetB_6.setText(_translate("MainWindow", "Run Details"))
        self.casN_62.setText(_translate("MainWindow", "6"))
        self.setupB_6.setText(_translate("MainWindow", "Setup Run"))
        self.runDefault_6.setText(_translate("MainWindow", "Run Default"))
        self.casN_63.setText(_translate("MainWindow", "6"))
        self.noCas_6.setText(_translate("MainWindow", "No cassette detected"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLoad_Program.setTitle(_translate("MainWindow", "Load Program"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

