#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 29 14:56:31 2020

@author: jackr
"""
from PyQt5 import QtCore, QtGui, QtWidgets

class ProtEditor(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setObjectName("protEditor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.delStepButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delStepButton.sizePolicy().hasHeightForWidth())
        self.delStepButton.setSizePolicy(sizePolicy)
        self.delStepButton.setMinimumSize(QtCore.QSize(0, 50))
        self.delStepButton.setObjectName("delStepButton")
        self.delStepButton.setText("Delete Step")
        self.gridLayout_3.addWidget(self.delStepButton, 2, 15, 1, 1)
        
        self.backButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMinimumSize(QtCore.QSize(150, 50))
        self.backButton.setObjectName("backButton")
        self.backButton.setText("Back")
        self.gridLayout_3.addWidget(self.backButton, 14, 0, 1, 1)
        
        self.listOperations = QtWidgets.QListWidget(self)
        self.listOperations.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listOperations.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listOperations.setAlternatingRowColors(True)
        self.listOperations.setObjectName("listOperations")
        self.gridLayout_3.addWidget(self.listOperations, 3, 0, 11, 5)
        
        self.saveButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(100, 50))
        self.saveButton.setObjectName("saveButton")
        self.saveButton.setText("Save")
        self.gridLayout_3.addWidget(self.saveButton, 14, 15, 1, 1)
        
        self.protNLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protNLab.sizePolicy().hasHeightForWidth())
        self.protNLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.protNLab.setFont(font)
        self.protNLab.setObjectName("protNLab")
        self.protNLab.setText("Protocol Name:")
        self.gridLayout_3.addWidget(self.protNLab, 1, 0, 1, 1)
        
        self.listStep = QtWidgets.QListWidget(self)
        self.listStep.setObjectName("listStep")
        self.gridLayout_3.addWidget(self.listStep, 2, 11, 13, 4)
        
        self.operLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operLab.sizePolicy().hasHeightForWidth())
        self.operLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.operLab.setFont(font)
        self.operLab.setObjectName("operLab")
        self.operLab.setText("Operations:")
        self.gridLayout_3.addWidget(self.operLab, 2, 0, 1, 1)
        
        self.editButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        self.editButton.setMinimumSize(QtCore.QSize(0, 50))
        self.editButton.setObjectName("editButton")
        self.editButton.setText("Edit Step")
        self.gridLayout_3.addWidget(self.editButton, 6, 15, 1, 1)
        
        self.editProtName = QtWidgets.QLineEdit(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editProtName.sizePolicy().hasHeightForWidth())
        self.editProtName.setSizePolicy(sizePolicy)
        self.editProtName.setMinimumSize(QtCore.QSize(0, 30))
        self.editProtName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.editProtName.setInputMask("")
        self.editProtName.setReadOnly(False)
        self.editProtName.setObjectName("editProtName")
        self.editProtName.setText("untitled")
        self.gridLayout_3.addWidget(self.editProtName, 1, 1, 1, 2)
        
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 2)
        
        spacerItem1 = QtWidgets.QSpacerItem(110, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 14, 1, 1, 1)
        
        self.newButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newButton.sizePolicy().hasHeightForWidth())
        self.newButton.setSizePolicy(sizePolicy)
        self.newButton.setMinimumSize(QtCore.QSize(100, 50))
        self.newButton.setObjectName("newButton")
        self.newButton.setText("New")
        self.gridLayout_3.addWidget(self.newButton, 14, 2, 1, 1)
        
        self.saveAsButton = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsButton.sizePolicy().hasHeightForWidth())
        self.saveAsButton.setSizePolicy(sizePolicy)
        self.saveAsButton.setMinimumSize(QtCore.QSize(100, 50))
        self.saveAsButton.setObjectName("saveAsButton")
        self.saveAsButton.setText("Save As")
        self.gridLayout_3.addWidget(self.saveAsButton, 13, 15, 1, 1)
        
        self.stepsLab = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsLab.sizePolicy().hasHeightForWidth())
        self.stepsLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stepsLab.setFont(font)
        self.stepsLab.setObjectName("stepsLab")
        self.stepsLab.setText("Steps in Protocol:")
        self.gridLayout_3.addWidget(self.stepsLab, 1, 11, 1, 2)
        
        
        
        # self.stackedWidget.addWidget(self.protEditor)
        
        # self.mainMonitor = QtWidgets.QWidget()
        # self.mainMonitor.setObjectName("mainMonitor")
        # self.gridLayout_2 = QtWidgets.QGridLayout(self.mainMonitor)
        # self.gridLayout_2.setObjectName("gridLayout_2")