#!/bin/bash
killbg() {
        for p in "${pids[@]}" ; do
                kill "$p";
        done
}
trap '' INT TSTP
source /home/jackr/.bashrc
source ~/prepbot/bin/activate
cd /home/jackr/SampleMonitor/Git/CasQML
python runApp.py

trap killbg EXIT
pids=()
background job 1 & 
pids+=($!)
background job 2... & 
pids+=($!)
foreground job

