#!/bin/bash
killbg() {
        for p in "${pids[@]}" ; do
                kill "$p";
        done
}
trap '' INT TSTP
source ~/.bashrc
ContainerID=$(sudo docker ps -aqf "name=crossbar")
echo "ContainerID: $ContainerID"
#echo $contID
if [ -z "$ContainerID" ]
then
    echo "ContainerID is empty, making crossbar container..."
    sudo docker run --name=crossbar --rm -d -p 8080:8080 crossbario/crossbar-armhf
else
    echo "ContainerID is not empty, checking status of crossbar container..."
    rID=$(sudo docker ps -aq --filter "name=crossbar" --filter "status=running")
    if [ -z "$rID" ]
    then
        echo "The container is stopped/not running... restarting..."
        sudo docker stop $(sudo docker ps -aqf "name=crossbar")
        sudo docker rm $(sudo docker ps -aqf "name=crossbar")
        sudo docker run --name=crossbar --rm -d -p 8080:8080 crossbario/crossbar-armhf
    else
        echo "The crossbar container is running! Skipping making new crossbar container..."
    fi
fi
    
source activate base
cd ~/CasMonitor
python runApp.py

trap killbg EXIT
pids=()
background job 1 & 
pids+=($!)
background job 2... & 
pids+=($!)
foreground job
