parameters:
  mixSpeed: 1.0
  incSpeed: 0.2
  removeSpeed: 1.0
  wasteSpeed: 4.0
  fillLineSpeed: 1.0
  fillSyrSpeed: 1.0
  washSyrSpeed: 1.0
  densSpeed: 0.2
  densVol: 0.1
  LINEVOL: 0.75
  removeVol: 1.5
  purgeVol: 4.0
  settleTime: 20.0
  reagentDensOrder:
    babb: 2
    formalin: 1
    meoh: 0
    unk: 1
    vial: 0
