#!/usr/bin/env python3

import machine
from time import sleep

LINEVOL = 0.75

def countdown(t):
	while t:
		mins, secs = divmod(t, 60)
		timer = '{:02d}:{:02d}'.format(mins, secs)
		print(timer, end="\r")
		sleep(1)
		t -=1

print('STARTING...')
#machine.connect()
#machine.home()
machine.engage_sampleF()

print('ADDING FORMALIN')
machine.goto_formalin()
machine.pump_in(1)
sleep(1)
machine.goto_sampleF()
machine.pump_out(LINEVOL)
machine.pump_out(0.5, 1)
#machine.release()
countdown(10)
print('REMOVING FORMALIN')
machine.pump_in(1.5)
sleep(2)
machine.goto_waste()
machine.pump_out(1.5)

print('WASHING SYRINGE')
machine.goto_meoh()
machine.pump_in(1)
sleep(1)
machine.goto_waste()
machine.pump_out(1)
sleep(1)
#machine.release()

#######################
print('MEOH WASHING SAMPLE')
machine.goto_meoh()
machine.pump_in(1)
sleep(1)
machine.goto_sampleF()
machine.pump_out(LINEVOL)
sleep(1)
machine.pump_out(0.6, 0.2)
countdown(300)

print('REMOVING MEOH WASH')
machine.pump_in(0.6)
sleep(1)
machine.pump_in(1.2)
sleep(1)
machine.goto_waste()
machine.pump_out(1.2)
sleep(1)

print('ADDING DYE')
machine.goto_vial()
machine.pump_in(1.3)
sleep(1)
machine.goto_sampleF()
machine.pump_out(LINEVOL)
sleep(2)
machine.pump_out(0.7)
#machine.release()


print('INCUBATING DYE')
countdown(300)
less_dye_in = 0.1
num_cycles = 1
for x in range(num_cycles):
	print('CYCLE : {:02d}'.format(x+1))
	machine.pump_in(0.6, 0.2)
	less_dye_in = 0.6-less_dye_in
	machine.pump_out(less_dye_in, 0.2)
	#machine.release()
	print('CYCLE : {:02d} of {:02d}'.format(x+1, num_cycles))
	countdown(3300)

print('REMOVING DYE')
machine.pump_in(1.5)
sleep(1)
machine.goto_waste()
machine.pump_out(1)

print('ADDING BABB')
machine.goto_babb()
machine.pump_in(1, 1)
sleep(5)
machine.goto_sampleF()
machine.pump_out(0.8, 1)
sleep(2)
machine.pump_out(0.4, 0.2)
#machine.release()
countdown(300)
machine.pump_out(0.2, 0.2)

print('BABB FINAL WASH')
#machine.pump_in(0.5)
#sleep(2)
#machine.pump_in(1)
#sleep(3)
#machine.goto_waste()
#machine.pump_out(1)
#sleep(2)
#machine.goto_babb()
#machine.pump_in(0.8, 1)
#sleep(2)
#machine.goto_sampleF()
#machine.pump_out(0.8, 0.5)
#sleep(2)
#machine.pump_out(0.4, 0.2)
#machine.release()
#countdown(2)
#machine.pump_out(0.3, 0.2)
#sleep(2)
machine.disengage_sampleF()
print('Specimen may be removed')

print('CLEANING')
machine.pump_in(1, 0.5)
sleep(2)
machine.pump_in(1, 0.5)
sleep(2)
machine.goto_waste()
machine.pump_out(0.7, 0.5)
sleep(2)
machine.goto_meoh()
machine.pump_in(1, 0.5)
sleep(2)
machine.goto_sampleF()
machine.pump_out(0.6, 0.5)
sleep(5)
machine.pump_in(0.7, 0.5)
sleep(2)
machine.goto_waste()
machine.pump_out(0.7)
sleep(2)
machine.release()
